services:
  - type: web
    name: emisora-2-0
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: APP_BASE_URL
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: default
